### ISSUE TITLE
prezto

### ISSUE THREAD

**Issue by ghost** [luugiathuy/dotfiles#2]
hiện em cũng đang sử dụng prezto này, em muốn để nó vào trong dotfile như trước em dùng ohmyzsh thì làm cách nào anh nhỉ. tại một lần cài prezto qua một máy nó đều hiên thị ln: file exists?

**Comment by luugiathuy** [comment]
Hi @henryvulcan , anh vừa update cái README, lúc install cái prezto, mình ko cần phải create cái links (không cần làm step này `Create a new Zsh configuration by copying/linking the Zsh configuration files provided:`) do e đã có mấy cái config files rồi.
